# Numpy

## numpy的属性

In [2]:
import numpy as np

array = np.array([[1, 2, 3],
                 [2, 3, 4]])
print(array)
print('number of dim:', array.ndim)
print('shape:', array.shape)
print('size:', array.size)

[[1 2 3]
 [2 3 4]]
number of dim: 2
shape: (2, 3)
size: 6


## numpy创建array

In [4]:
a = np.array([2, 3, 4], dtype=np.int)
print(a.dtype)

int32


In [5]:
a = np.zeros((3, 4))
print(a)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [9]:
a = np.ones((3, 4), dtype=np.int16)
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [13]:
a = np.empty((3, 4))
print(a)

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [14]:
a = np.arange(10, 20, 2)
print(a)

[10 12 14 16 18]


In [15]:
a = np.arange(12).reshape((3, 4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## numpy的基础运算

In [20]:
a = np.array([10, 20, 30, 40])
b = np.array([0, 1, 2, 3])

print(a - b)

[10 19 28 37]


In [21]:
print(a + b)

[10 21 32 43]


In [22]:
print(b ** 2)

[0 1 4 9]


In [26]:
print(10 * np.sin(a))

[-5.44021111  9.12945251 -9.88031624  7.4511316 ]


In [25]:
print(b)
print(b < 3)

[0 1 2 3]
[ True  True  True False]


In [29]:
a = np.array([[1, 1],
             [0, 1]])
b = np.arange(4).reshape((2, 2))

# 逐个相乘
print(a * b)
# 矩阵乘法
print(np.dot(a, b))
print(a.dot(b))

[[0 1]
 [0 3]]
[[2 4]
 [2 3]]
[[2 4]
 [2 3]]


In [30]:
# 生成0-1之间的一个数
a = np.random.random((2, 4))
print(a)

[[ 0.26322264  0.372595    0.72988923  0.04764845]
 [ 0.06310322  0.12035294  0.46958708  0.47979094]]


In [33]:
# axis, 0:每行求和， 1:每列求和
print(np.sum(a, axis=1))
print(np.min(a, axis=0))
print(np.max(a, axis=1))

[ 1.41335532  1.13283418]
[ 0.06310322  0.12035294  0.46958708  0.04764845]
[ 0.72988923  0.47979094]


In [34]:
A = np.arange(2, 14).reshape((3, 4))

print(A)

# 计算索引
print(np.argmin(A))
print(np.argmax(A))

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
0
11


In [35]:
# 计算平均值
print(A.mean())
print(np.average(A))

7.5
7.5


In [36]:
# 计算中位数
print(np.median(A))

7.5


In [39]:
# 逐步累加
print(A.reshape(1, 12))
print(np.cumsum(A))

[[ 2  3  4  5  6  7  8  9 10 11 12 13]]
[ 2  5  9 14 20 27 35 44 54 65 77 90]


In [41]:
# 每行数之间的差
print(A)
print(np.diff(A))

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [42]:
# 判断是否为0, 返回两个数组：非零数的行数组、列数组
print(np.nonzero(A))

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))


In [43]:
# 逐行排序
A = np.arange(14, 2, -1).reshape((3, 4))
print(A)
print(np.sort(A))

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]


In [45]:
# 矩阵的转置
print(A)
print(np.transpose(A))
print(A.T)
print(A.T.dot(A))

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[332 302 272 242]
 [302 275 248 221]
 [272 248 224 200]
 [242 221 200 179]]


In [46]:
# 过滤重新赋值，所有小于5的数都变为5，所有大于9的数都变为9
print(A)
print(np.clip(A, 5, 9))

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[[9 9 9 9]
 [9 9 8 7]
 [6 5 5 5]]


In [47]:
# 对于行计算，axis=0; 对于列计算，axis=1
print(A)
print(np.mean(A, axis=0))
print(np.mean(A, axis=1))

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[ 10.   9.   8.   7.]
[ 12.5   8.5   4.5]
